# Adjust region / stack_name to your account. No secrets belong here.

version = 0.1

[default.global.parameters]
stack_name = "weekly-sharing-reminder-api"
template_file = "sam/template.yaml"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
region = "ap-southeast-1"
confirm_changeset = true
s3_prefix = "weekly-sharing-reminder-api"
profile = "tingcccc-admin"
image_repositories = []
