version = 0.1
[default.deploy.parameters]
stack_name = "weekly-sharing-reminder-api"
resolve_s3 = true
s3_prefix = "weekly-sharing-reminder-api"
region = "ap-southeast-1"
profile = "tingcccc-admin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoDomainPrefix=\"weekly-sharing-reminder-auth\" AuthCallbackUrl=\"http://localhost:8080/\" AuthLogoutUrl=\"http://localhost:8080/\""
image_repositories = []
